# Podfile for IDOS iOS App
# Provides crypto dependencies for NaCl Box encryption and SCrypt

platform :ios, '15.0'

target 'iosApp' do
  use_frameworks!
  # TrustWalletCore for Ethereum wallet operations (BIP39/BIP44/secp256k1)
  # Mature, production-proven library from Trust Wallet
  pod 'TrustWalletCore', '~> 4.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end