name: Android Instrumentation Tests

on:
  workflow_dispatch:

jobs:
  instrumentation-tests:
    name: Android Instrumentation Tests
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Enable KVM for hardware acceleration
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          sudo usermod -a -G kvm $USER

      - name: Create .env for tests from GitHub Secrets
        shell: bash
        env:
            MNEMONIC_WORDS: ${{ secrets.MNEMONIC_WORDS }}
            PASSWORD: ${{ secrets.PASSWORD }}
        run: |
            # Write .env used by dotenv-kotlin in tests. Values come from repository secrets.
            cat > .env <<EOF
            MNEMONIC_WORDS=$MNEMONIC_WORDS
            PASSWORD=$PASSWORD
            EOF
            echo ".env created with test credentials"

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-34

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: echo "Generated AVD snapshot for caching."

      - name: Run instrumentation tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            echo "Running Android instrumentation tests..."
            ./gradlew :androidApp:connectedCheck --stacktrace --no-daemon

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-instrumentation-test-reports
          path: |
            androidApp/build/reports/androidTests/**
            androidApp/build/outputs/androidTest-results/**
          if-no-files-found: ignore

      - name: Publish test results
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/build/outputs/androidTest-results/**/TEST-*.xml'
          check_name: 'Android Instrumentation Test Results'
          require_tests: false
