name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  build-and-test:
    # Skip CI if commit was made by GitHub Actions (e.g., Package.swift updates from release workflow)
    if: github.actor != 'github-actions[bot]'
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yml
    secrets:
      MNEMONIC_WORDS: ${{ secrets.MNEMONIC_WORDS }}
      PASSWORD: ${{ secrets.PASSWORD }}
