name: CI

on:
  push:
    branches: [ main, develop, "feature/**", "fix/**" ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Lint, Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      # Ktlint formatting and style checks (does not require Gradle plugin)
      - name: Run ktlint
        uses: ktlint/actions/ktlint@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          android: false
          fail_on_error: true

      # Detekt static analysis (does not require Gradle plugin)
      - name: Run detekt
        uses: detekt/detekt-action@v1
        with:
          arguments: --build-upon-default-config --all-rules --parallel --base-path .
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (includes tests)
        run: ./gradlew build --stacktrace --no-daemon

      # Optionally run target-specific tests explicitly if needed (uncomment as necessary)
      # - name: JVM tests
      #   run: ./gradlew jvmTest --no-daemon
      # - name: Android unit tests
      #   run: ./gradlew testDebugUnitTest --no-daemon

      - name: Publish Test Report (if present)
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/build/test-results/test/*.xml'
          require_tests: false

      - name: Upload detekt report (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: |
            **/build/reports/detekt/*.html
            **/build/reports/detekt/*.xml
          if-no-files-found: ignore
