name: CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Lint, Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Lint (ktlint + detekt)
        run: ./gradlew ktlintCheck detekt --stacktrace --no-daemon

      - name: Build (includes tests)
        run: ./gradlew build --stacktrace --no-daemon

      # Optionally run target-specific tests explicitly if needed (uncomment as necessary)
      # - name: JVM tests
      #   run: ./gradlew jvmTest --no-daemon
      # - name: Android unit tests
      #   run: ./gradlew testDebugUnitTest --no-daemon

      - name: Publish Test Report (if present)
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/build/test-results/test/*.xml'
          require_tests: false

      - name: Upload lint reports (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: |
            **/build/reports/detekt/*.html
            **/build/reports/detekt/*.xml
            **/build/reports/ktlint/*.xml
          if-no-files-found: ignore
