name: iOS UI Tests

on:
  workflow_dispatch:

jobs:
  test:
    name: iOS UI Tests
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Create .env for tests from GitHub Secrets
        shell: bash
        env:
            MNEMONIC_WORDS: ${{ secrets.MNEMONIC_WORDS }}
            PASSWORD: ${{ secrets.PASSWORD }}
        run: |
            # Write .env used by dotenv-kotlin in tests. Values come from repository secrets.
            cat > .env <<EOF
            MNEMONIC_WORDS=$MNEMONIC_WORDS
            PASSWORD=$PASSWORD
            EOF
            echo ".env created with test credentials"

      - name: Build for testing
        run: |
          cd iosApp
          xcodebuild \
            -project iosApp.xcodeproj \
            -scheme iosApp \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -derivedDataPath DerivedData \
            build-for-testing

      - name: Run UI tests
        run: |
          cd iosApp
          xcodebuild \
            -project iosApp.xcodeproj \
            -scheme iosApp \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -derivedDataPath DerivedData \
            -resultBundlePath TestResults \
            test-without-building

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-test-results
          path: iosApp/TestResults.xcresult
          if-no-files-found: ignore
